# Generated by Django 4.0.2 on 2022-03-04 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="News",
            new_name="NewsPost",
        ),
    ]
