# Generated by Django 4.0.2 on 2022-03-04 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_newspost_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newspost',
            old_name='image',
            new_name='media_link',
        ),
    ]
