# Generated by Django 4.0.3 on 2022-03-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_rename_image_newspost_media_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newspost",
            name="date",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
