# Generated by Django 4.0.3 on 2022-03-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0005_alter_newspost_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="newspost",
            name="epoch",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
