# Generated by Django 4.0.3 on 2022-03-04 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_newspost_epoch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspost',
            options={'ordering': ['-epoch']},
        ),
    ]
