# Generated by Django 4.0.3 on 2022-03-04 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_newspost_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='newspost',
            unique_together={('title',)},
        ),
    ]
