# Generated by Django 4.0.3 on 2022-03-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0009_rename_media_link_newspost_image_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newspost",
            name="author_link",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
